# Generated by Django 3.2.12 on 2023-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageField',
            field=models.ImageField(default='/images/nitin.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
