# Generated by Django 3.2.12 on 2023-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_post_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageField',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/nitin.jpg', upload_to='', verbose_name='images/'),
            preserve_default=False,
        ),
    ]
